### ISSUE TITLE
Dead link in /learning/advanced

### ISSUE THREAD

**Issue by rogerxaic** [cloud-native-toolkit/developer-guide#274]
**Describe the bug**
In https://cloudnativetoolkit.dev/learning/advanced there is a link to "GitOps with ArgoCD" under "Continuous Delivery" which is dead.

**To Reproduce**
1. Go to 'https://cloudnativetoolkit.dev/learning/advanced'
2. Scroll down to 'Continuous Delivery'
3. Click on 'GitOps'
4. See error 404

**Additional context**
I guess this is due to a refactor on https://ibm-gsi-ecosystem.github.io. Seemingly, adding a `1` to the URL (i.e. from `developer-advanced` to `developer-advanced-1` : https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-advanced-1/gitops/) lets us access a webpage, but this is not listed in the menu on the left, which makes me think that the page *might* disappear. I don't know who manages the other page, but I reckon we should liaise with them.

**Comment by csantanapr** [comment]
the url change, check out this link https://cloudnativetoolkit.dev/learning/fast-cd/
