### ISSUE TITLE
shell.cloudnativetoolkit.dev doesn't follow redirects when trying to detect version (tar: Error opening archive: Unrecognized archive format)

### ISSUE THREAD

**Issue by markstur** [cloud-native-toolkit/developer-guide#308]
**Describe the bug**
download dev tools leads to:
tar: Error opening archive: Unrecognized archive format

I was trying to determine what line 3 will do...
L3: VERSION=$(curl -L --silent "https://api.github.com/repos/ibm-garage-cloud/cloud-shell-commands/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')

echo $VERSION
<echo nothing>

Try the curl command:

(base) markstur@Marks-MacBook-Pro cnt % curl --silent "https://api.github.com/repos/ibm-garage-cloud/cloud-shell-commands/releases/latest"                                                           
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/246656452/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}

**To Reproduce**
1. Step through the script
2. Try the version check

**Expected behavior**
Should follow redirect and properly detect version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  macOS

**Additional context**

To fix, add -L to the curl command on line 3 when it tries to detect the version.

(-L is to follow redirects)

**Comment by seansund** [comment]
Good catch. This is a result of the org rename. I'll get this fixed right away

**Comment by seansund** [comment]
@markstur This issue has been fixed
